server:
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
     nginx.org/hsts: "false"
     cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - host: argocd.eks.abdikarim-tech.com
    tls:
      - secretName: argocd-ingress-tls
        hosts:
          - argocd.eks.abdikarim-tech.com

