server:
  extraArgs:
    - --insecure
  
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "issuer"
    hostname: argocd.eks.abdikarim-tech.com
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.eks.abdikarim-tech.com