grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - grafana.eks.abdikarim-tech.com
    tls:
      - hosts:
          - grafana.eks.abdikarim-tech.com
        secretName: grafana-tls

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - prometheus.eks.abdikarim-tech.com
    tls:
      - hosts:
          - prometheus.eks.abdikarim-tech.com
        secretName: prometheus-tls