
FROM node:22-alpine AS build

WORKDIR /app

COPY app/package*.json app/yarn.lock ./

RUN yarn install

COPY app/ ./

RUN yarn build

FROM node:22-alpine AS prod

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/build /app/build

RUN addgroup -S nonroot && adduser -S nonroot -G nonroot

USER nonroot:nonroot

EXPOSE 3000

HEALTHCHECK CMD curl -f http://localhost:3000/ || exit 1

CMD ["serve", "-s", "build"]